//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HOSTAL.ENTIDADES
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_PRODUCTOS
    {
        public decimal ID_DETALLE { get; set; }
        public decimal CANTIDAD_SOLICITADA { get; set; }
        public decimal TOTAL_PRODUCTO { get; set; }
        public decimal ID_PRODUCTO { get; set; }
        public decimal ID_ORDENPEDIDO { get; set; }
        public Nullable<decimal> CANTIDAD_RECIBIDA { get; set; }
    
        public virtual ORDEN_PEDIDO ORDEN_PEDIDO { get; set; }
        public virtual PRODUCTO PRODUCTO { get; set; }
    }
}
