//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HOSTAL.ENTIDADES
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCTO()
        {
            this.DETALLE_PRODUCTOS = new HashSet<DETALLE_PRODUCTOS>();
        }
    
        public decimal ID_PRODUCTO { get; set; }
        public string NOMBRE_PRO { get; set; }
        public decimal PRECIO_PRO { get; set; }
        public decimal STOCK_PRO { get; set; }
        public Nullable<System.DateTime> FECHAVENCIMIENTO_PRO { get; set; }
        public string RUT_PROV { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_PRODUCTOS> DETALLE_PRODUCTOS { get; set; }
        public virtual PROVEEDOR PROVEEDOR { get; set; }
    }
}
