//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HOSTAL.ENTIDADES
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROVEEDOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROVEEDOR()
        {
            this.PRODUCTO = new HashSet<PRODUCTO>();
        }
    
        public string RUT_PROV { get; set; }
        public string NOMBRE_PROV { get; set; }
        public string APELLIDOPATERNO_PROV { get; set; }
        public string APELLIDOMATERNO_PRVO { get; set; }
        public Nullable<decimal> TELEFONO_PROV { get; set; }
        public string USUARIO_EMAIL { get; set; }
        public decimal ID_REGION { get; set; }
        public string EMPRESA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCTO> PRODUCTO { get; set; }
        public virtual REGION REGION { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
