//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HOSTAL.ENTIDADES
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECEPCION
    {
        public decimal ID_RECEPCION { get; set; }
        public decimal ID_PRODUCTO { get; set; }
        public decimal CANTIDAD { get; set; }
    }
}
