//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hostal.ENTIDADES
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    using HOSTAL.ENTIDADES;

    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<COMUNA> COMUNA { get; set; }
        public virtual DbSet<DETALLE_PRODUCTOS> DETALLE_PRODUCTOS { get; set; }
        public virtual DbSet<EMPLEADO> EMPLEADO { get; set; }
        public virtual DbSet<EMPRESA> EMPRESA { get; set; }
        public virtual DbSet<ESTADO_HABITACION> ESTADO_HABITACION { get; set; }
        public virtual DbSet<ESTADO_ORDENCOMPRA> ESTADO_ORDENCOMPRA { get; set; }
        public virtual DbSet<ESTADO_ORDENPEDIDO> ESTADO_ORDENPEDIDO { get; set; }
        public virtual DbSet<ESTADO_USUARIO> ESTADO_USUARIO { get; set; }
        public virtual DbSet<HABITACION> HABITACION { get; set; }
        public virtual DbSet<HUESPED> HUESPED { get; set; }
        public virtual DbSet<MENU> MENU { get; set; }
        public virtual DbSet<MINUTA_SEMANAL> MINUTA_SEMANAL { get; set; }
        public virtual DbSet<ORDEN_COMPRA> ORDEN_COMPRA { get; set; }
        public virtual DbSet<ORDEN_PEDIDO> ORDEN_PEDIDO { get; set; }
        public virtual DbSet<PLATOS_MINUTA> PLATOS_MINUTA { get; set; }
        public virtual DbSet<PRODUCTO> PRODUCTO { get; set; }
        public virtual DbSet<PROVEEDOR> PROVEEDOR { get; set; }
        public virtual DbSet<PROVINCIA> PROVINCIA { get; set; }
        public virtual DbSet<RECEPCION> RECEPCION { get; set; }
        public virtual DbSet<REGION> REGION { get; set; }
        public virtual DbSet<SEXO> SEXO { get; set; }
        public virtual DbSet<TIPO_USUARIO> TIPO_USUARIO { get; set; }
        public virtual DbSet<USUARIO> USUARIO { get; set; }
    
        public virtual int SP_CREAR_PEDIDO(Nullable<decimal> cANTIDAD_PRODUCTOS, Nullable<decimal> tOTAL, string rUTEMPLEADO, string eMAILEMPLEADO, string rUTPROVEEDOR, string eMAILPROVEEDOR)
        {
            var cANTIDAD_PRODUCTOSParameter = cANTIDAD_PRODUCTOS.HasValue ?
                new ObjectParameter("CANTIDAD_PRODUCTOS", cANTIDAD_PRODUCTOS) :
                new ObjectParameter("CANTIDAD_PRODUCTOS", typeof(decimal));
    
            var tOTALParameter = tOTAL.HasValue ?
                new ObjectParameter("TOTAL", tOTAL) :
                new ObjectParameter("TOTAL", typeof(decimal));
    
            var rUTEMPLEADOParameter = rUTEMPLEADO != null ?
                new ObjectParameter("RUTEMPLEADO", rUTEMPLEADO) :
                new ObjectParameter("RUTEMPLEADO", typeof(string));
    
            var eMAILEMPLEADOParameter = eMAILEMPLEADO != null ?
                new ObjectParameter("EMAILEMPLEADO", eMAILEMPLEADO) :
                new ObjectParameter("EMAILEMPLEADO", typeof(string));
    
            var rUTPROVEEDORParameter = rUTPROVEEDOR != null ?
                new ObjectParameter("RUTPROVEEDOR", rUTPROVEEDOR) :
                new ObjectParameter("RUTPROVEEDOR", typeof(string));
    
            var eMAILPROVEEDORParameter = eMAILPROVEEDOR != null ?
                new ObjectParameter("EMAILPROVEEDOR", eMAILPROVEEDOR) :
                new ObjectParameter("EMAILPROVEEDOR", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CREAR_PEDIDO", cANTIDAD_PRODUCTOSParameter, tOTALParameter, rUTEMPLEADOParameter, eMAILEMPLEADOParameter, rUTPROVEEDORParameter, eMAILPROVEEDORParameter);
        }
    
        public virtual int SP_DETALLE_PEDIDO(Nullable<decimal> cANTSOLICITADA, Nullable<decimal> iDPRODUCTO, Nullable<decimal> iD_PEDIDO)
        {
            var cANTSOLICITADAParameter = cANTSOLICITADA.HasValue ?
                new ObjectParameter("CANTSOLICITADA", cANTSOLICITADA) :
                new ObjectParameter("CANTSOLICITADA", typeof(decimal));
    
            var iDPRODUCTOParameter = iDPRODUCTO.HasValue ?
                new ObjectParameter("IDPRODUCTO", iDPRODUCTO) :
                new ObjectParameter("IDPRODUCTO", typeof(decimal));
    
            var iD_PEDIDOParameter = iD_PEDIDO.HasValue ?
                new ObjectParameter("ID_PEDIDO", iD_PEDIDO) :
                new ObjectParameter("ID_PEDIDO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DETALLE_PEDIDO", cANTSOLICITADAParameter, iDPRODUCTOParameter, iD_PEDIDOParameter);
        }
    
        public virtual int SP_INSERTAR_CANTIDADPRODUCTOS(Nullable<decimal> iDPRODUCTO, Nullable<decimal> cANTSOLICITADA)
        {
            var iDPRODUCTOParameter = iDPRODUCTO.HasValue ?
                new ObjectParameter("IDPRODUCTO", iDPRODUCTO) :
                new ObjectParameter("IDPRODUCTO", typeof(decimal));
    
            var cANTSOLICITADAParameter = cANTSOLICITADA.HasValue ?
                new ObjectParameter("CANTSOLICITADA", cANTSOLICITADA) :
                new ObjectParameter("CANTSOLICITADA", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_INSERTAR_CANTIDADPRODUCTOS", iDPRODUCTOParameter, cANTSOLICITADAParameter);
        }
    
        public virtual int SP_INSERTAR_COMPRA(Nullable<System.DateTime> fECHAINGRESO, Nullable<System.DateTime> fECHASALIDA, string rUTHUESPED, Nullable<decimal> nRO_HABITACION, string eMPLEADO_RUT)
        {
            var fECHAINGRESOParameter = fECHAINGRESO.HasValue ?
                new ObjectParameter("FECHAINGRESO", fECHAINGRESO) :
                new ObjectParameter("FECHAINGRESO", typeof(System.DateTime));
    
            var fECHASALIDAParameter = fECHASALIDA.HasValue ?
                new ObjectParameter("FECHASALIDA", fECHASALIDA) :
                new ObjectParameter("FECHASALIDA", typeof(System.DateTime));
    
            var rUTHUESPEDParameter = rUTHUESPED != null ?
                new ObjectParameter("RUTHUESPED", rUTHUESPED) :
                new ObjectParameter("RUTHUESPED", typeof(string));
    
            var nRO_HABITACIONParameter = nRO_HABITACION.HasValue ?
                new ObjectParameter("NRO_HABITACION", nRO_HABITACION) :
                new ObjectParameter("NRO_HABITACION", typeof(decimal));
    
            var eMPLEADO_RUTParameter = eMPLEADO_RUT != null ?
                new ObjectParameter("EMPLEADO_RUT", eMPLEADO_RUT) :
                new ObjectParameter("EMPLEADO_RUT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_INSERTAR_COMPRA", fECHAINGRESOParameter, fECHASALIDAParameter, rUTHUESPEDParameter, nRO_HABITACIONParameter, eMPLEADO_RUTParameter);
        }
    
        public virtual int SP_INSERTAR_EMPLEADO(string rUTEMPLEADO, string nOMBRE, string aPELLIDOP, string aPELLIDOM, Nullable<System.DateTime> fECHANACIMIENTO, Nullable<decimal> tELEFONO, Nullable<System.DateTime> fECHAINGRESO, string eMAIL_USUARIO, Nullable<decimal> iDSEXO, Nullable<decimal> iDESTADOUSUARIO, Nullable<decimal> iDTIPOUSUARIO, string cONTRASENA)
        {
            var rUTEMPLEADOParameter = rUTEMPLEADO != null ?
                new ObjectParameter("RUTEMPLEADO", rUTEMPLEADO) :
                new ObjectParameter("RUTEMPLEADO", typeof(string));
    
            var nOMBREParameter = nOMBRE != null ?
                new ObjectParameter("NOMBRE", nOMBRE) :
                new ObjectParameter("NOMBRE", typeof(string));
    
            var aPELLIDOPParameter = aPELLIDOP != null ?
                new ObjectParameter("APELLIDOP", aPELLIDOP) :
                new ObjectParameter("APELLIDOP", typeof(string));
    
            var aPELLIDOMParameter = aPELLIDOM != null ?
                new ObjectParameter("APELLIDOM", aPELLIDOM) :
                new ObjectParameter("APELLIDOM", typeof(string));
    
            var fECHANACIMIENTOParameter = fECHANACIMIENTO.HasValue ?
                new ObjectParameter("FECHANACIMIENTO", fECHANACIMIENTO) :
                new ObjectParameter("FECHANACIMIENTO", typeof(System.DateTime));
    
            var tELEFONOParameter = tELEFONO.HasValue ?
                new ObjectParameter("TELEFONO", tELEFONO) :
                new ObjectParameter("TELEFONO", typeof(decimal));
    
            var fECHAINGRESOParameter = fECHAINGRESO.HasValue ?
                new ObjectParameter("FECHAINGRESO", fECHAINGRESO) :
                new ObjectParameter("FECHAINGRESO", typeof(System.DateTime));
    
            var eMAIL_USUARIOParameter = eMAIL_USUARIO != null ?
                new ObjectParameter("EMAIL_USUARIO", eMAIL_USUARIO) :
                new ObjectParameter("EMAIL_USUARIO", typeof(string));
    
            var iDSEXOParameter = iDSEXO.HasValue ?
                new ObjectParameter("IDSEXO", iDSEXO) :
                new ObjectParameter("IDSEXO", typeof(decimal));
    
            var iDESTADOUSUARIOParameter = iDESTADOUSUARIO.HasValue ?
                new ObjectParameter("IDESTADOUSUARIO", iDESTADOUSUARIO) :
                new ObjectParameter("IDESTADOUSUARIO", typeof(decimal));
    
            var iDTIPOUSUARIOParameter = iDTIPOUSUARIO.HasValue ?
                new ObjectParameter("IDTIPOUSUARIO", iDTIPOUSUARIO) :
                new ObjectParameter("IDTIPOUSUARIO", typeof(decimal));
    
            var cONTRASENAParameter = cONTRASENA != null ?
                new ObjectParameter("CONTRASENA", cONTRASENA) :
                new ObjectParameter("CONTRASENA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_INSERTAR_EMPLEADO", rUTEMPLEADOParameter, nOMBREParameter, aPELLIDOPParameter, aPELLIDOMParameter, fECHANACIMIENTOParameter, tELEFONOParameter, fECHAINGRESOParameter, eMAIL_USUARIOParameter, iDSEXOParameter, iDESTADOUSUARIOParameter, iDTIPOUSUARIOParameter, cONTRASENAParameter);
        }
    
        public virtual int SP_INSERTAR_EMPRESA(string rUTEMPRESA, string nOMBRE_EMPRESA, string rAZONSOCIAL, Nullable<decimal> tELEFONO, Nullable<decimal> iDREGION, string eMAIL, Nullable<decimal> iDESTADOUSUARIO, string cONTRASENA)
        {
            var rUTEMPRESAParameter = rUTEMPRESA != null ?
                new ObjectParameter("RUTEMPRESA", rUTEMPRESA) :
                new ObjectParameter("RUTEMPRESA", typeof(string));
    
            var nOMBRE_EMPRESAParameter = nOMBRE_EMPRESA != null ?
                new ObjectParameter("NOMBRE_EMPRESA", nOMBRE_EMPRESA) :
                new ObjectParameter("NOMBRE_EMPRESA", typeof(string));
    
            var rAZONSOCIALParameter = rAZONSOCIAL != null ?
                new ObjectParameter("RAZONSOCIAL", rAZONSOCIAL) :
                new ObjectParameter("RAZONSOCIAL", typeof(string));
    
            var tELEFONOParameter = tELEFONO.HasValue ?
                new ObjectParameter("TELEFONO", tELEFONO) :
                new ObjectParameter("TELEFONO", typeof(decimal));
    
            var iDREGIONParameter = iDREGION.HasValue ?
                new ObjectParameter("IDREGION", iDREGION) :
                new ObjectParameter("IDREGION", typeof(decimal));
    
            var eMAILParameter = eMAIL != null ?
                new ObjectParameter("EMAIL", eMAIL) :
                new ObjectParameter("EMAIL", typeof(string));
    
            var iDESTADOUSUARIOParameter = iDESTADOUSUARIO.HasValue ?
                new ObjectParameter("IDESTADOUSUARIO", iDESTADOUSUARIO) :
                new ObjectParameter("IDESTADOUSUARIO", typeof(decimal));
    
            var cONTRASENAParameter = cONTRASENA != null ?
                new ObjectParameter("CONTRASENA", cONTRASENA) :
                new ObjectParameter("CONTRASENA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_INSERTAR_EMPRESA", rUTEMPRESAParameter, nOMBRE_EMPRESAParameter, rAZONSOCIALParameter, tELEFONOParameter, iDREGIONParameter, eMAILParameter, iDESTADOUSUARIOParameter, cONTRASENAParameter);
        }
    
        public virtual int SP_INSERTAR_HUESPED(string rUTHUESPED, string nOMBRE, string aPELLIDOP, string aPELLIDOM, Nullable<decimal> tELEFONO, string rUTEMPRESA, Nullable<decimal> iDSEXO)
        {
            var rUTHUESPEDParameter = rUTHUESPED != null ?
                new ObjectParameter("RUTHUESPED", rUTHUESPED) :
                new ObjectParameter("RUTHUESPED", typeof(string));
    
            var nOMBREParameter = nOMBRE != null ?
                new ObjectParameter("NOMBRE", nOMBRE) :
                new ObjectParameter("NOMBRE", typeof(string));
    
            var aPELLIDOPParameter = aPELLIDOP != null ?
                new ObjectParameter("APELLIDOP", aPELLIDOP) :
                new ObjectParameter("APELLIDOP", typeof(string));
    
            var aPELLIDOMParameter = aPELLIDOM != null ?
                new ObjectParameter("APELLIDOM", aPELLIDOM) :
                new ObjectParameter("APELLIDOM", typeof(string));
    
            var tELEFONOParameter = tELEFONO.HasValue ?
                new ObjectParameter("TELEFONO", tELEFONO) :
                new ObjectParameter("TELEFONO", typeof(decimal));
    
            var rUTEMPRESAParameter = rUTEMPRESA != null ?
                new ObjectParameter("RUTEMPRESA", rUTEMPRESA) :
                new ObjectParameter("RUTEMPRESA", typeof(string));
    
            var iDSEXOParameter = iDSEXO.HasValue ?
                new ObjectParameter("IDSEXO", iDSEXO) :
                new ObjectParameter("IDSEXO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_INSERTAR_HUESPED", rUTHUESPEDParameter, nOMBREParameter, aPELLIDOPParameter, aPELLIDOMParameter, tELEFONOParameter, rUTEMPRESAParameter, iDSEXOParameter);
        }
    
        public virtual int SP_INSERTAR_PEDIDO(Nullable<System.DateTime> fECHAPEDIDO, string rUT_EMP)
        {
            var fECHAPEDIDOParameter = fECHAPEDIDO.HasValue ?
                new ObjectParameter("FECHAPEDIDO", fECHAPEDIDO) :
                new ObjectParameter("FECHAPEDIDO", typeof(System.DateTime));
    
            var rUT_EMPParameter = rUT_EMP != null ?
                new ObjectParameter("RUT_EMP", rUT_EMP) :
                new ObjectParameter("RUT_EMP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_INSERTAR_PEDIDO", fECHAPEDIDOParameter, rUT_EMPParameter);
        }
    
        public virtual int SP_INSERTAR_PRODUCTOS(string nOMBRE_PRO, Nullable<decimal> pRECIO, Nullable<decimal> sTOCK, Nullable<System.DateTime> fECHA_VENCIMIENTO, string rUT_PROV)
        {
            var nOMBRE_PROParameter = nOMBRE_PRO != null ?
                new ObjectParameter("NOMBRE_PRO", nOMBRE_PRO) :
                new ObjectParameter("NOMBRE_PRO", typeof(string));
    
            var pRECIOParameter = pRECIO.HasValue ?
                new ObjectParameter("PRECIO", pRECIO) :
                new ObjectParameter("PRECIO", typeof(decimal));
    
            var sTOCKParameter = sTOCK.HasValue ?
                new ObjectParameter("STOCK", sTOCK) :
                new ObjectParameter("STOCK", typeof(decimal));
    
            var fECHA_VENCIMIENTOParameter = fECHA_VENCIMIENTO.HasValue ?
                new ObjectParameter("FECHA_VENCIMIENTO", fECHA_VENCIMIENTO) :
                new ObjectParameter("FECHA_VENCIMIENTO", typeof(System.DateTime));
    
            var rUT_PROVParameter = rUT_PROV != null ?
                new ObjectParameter("RUT_PROV", rUT_PROV) :
                new ObjectParameter("RUT_PROV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_INSERTAR_PRODUCTOS", nOMBRE_PROParameter, pRECIOParameter, sTOCKParameter, fECHA_VENCIMIENTOParameter, rUT_PROVParameter);
        }
    
        public virtual int SP_INSERTAR_PROVEEDOR(string rUTPROVEEDOR, string nOMBRE, string aPELLIDOP, string aPELLIDOM, Nullable<decimal> tELEFONO, string eMAIL_USUARIO, Nullable<decimal> iDREGION, string eMPRESA, Nullable<decimal> iDESTADOUSUARIO, string cONTRASENA)
        {
            var rUTPROVEEDORParameter = rUTPROVEEDOR != null ?
                new ObjectParameter("RUTPROVEEDOR", rUTPROVEEDOR) :
                new ObjectParameter("RUTPROVEEDOR", typeof(string));
    
            var nOMBREParameter = nOMBRE != null ?
                new ObjectParameter("NOMBRE", nOMBRE) :
                new ObjectParameter("NOMBRE", typeof(string));
    
            var aPELLIDOPParameter = aPELLIDOP != null ?
                new ObjectParameter("APELLIDOP", aPELLIDOP) :
                new ObjectParameter("APELLIDOP", typeof(string));
    
            var aPELLIDOMParameter = aPELLIDOM != null ?
                new ObjectParameter("APELLIDOM", aPELLIDOM) :
                new ObjectParameter("APELLIDOM", typeof(string));
    
            var tELEFONOParameter = tELEFONO.HasValue ?
                new ObjectParameter("TELEFONO", tELEFONO) :
                new ObjectParameter("TELEFONO", typeof(decimal));
    
            var eMAIL_USUARIOParameter = eMAIL_USUARIO != null ?
                new ObjectParameter("EMAIL_USUARIO", eMAIL_USUARIO) :
                new ObjectParameter("EMAIL_USUARIO", typeof(string));
    
            var iDREGIONParameter = iDREGION.HasValue ?
                new ObjectParameter("IDREGION", iDREGION) :
                new ObjectParameter("IDREGION", typeof(decimal));
    
            var eMPRESAParameter = eMPRESA != null ?
                new ObjectParameter("EMPRESA", eMPRESA) :
                new ObjectParameter("EMPRESA", typeof(string));
    
            var iDESTADOUSUARIOParameter = iDESTADOUSUARIO.HasValue ?
                new ObjectParameter("IDESTADOUSUARIO", iDESTADOUSUARIO) :
                new ObjectParameter("IDESTADOUSUARIO", typeof(decimal));
    
            var cONTRASENAParameter = cONTRASENA != null ?
                new ObjectParameter("CONTRASENA", cONTRASENA) :
                new ObjectParameter("CONTRASENA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_INSERTAR_PROVEEDOR", rUTPROVEEDORParameter, nOMBREParameter, aPELLIDOPParameter, aPELLIDOMParameter, tELEFONOParameter, eMAIL_USUARIOParameter, iDREGIONParameter, eMPRESAParameter, iDESTADOUSUARIOParameter, cONTRASENAParameter);
        }
    
        public virtual int SP_RECIBIR_PEDIDO(Nullable<decimal> iDPEDIDO, string pEDIDORECIBIDO)
        {
            var iDPEDIDOParameter = iDPEDIDO.HasValue ?
                new ObjectParameter("IDPEDIDO", iDPEDIDO) :
                new ObjectParameter("IDPEDIDO", typeof(decimal));
    
            var pEDIDORECIBIDOParameter = pEDIDORECIBIDO != null ?
                new ObjectParameter("PEDIDORECIBIDO", pEDIDORECIBIDO) :
                new ObjectParameter("PEDIDORECIBIDO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_RECIBIR_PEDIDO", iDPEDIDOParameter, pEDIDORECIBIDOParameter);
        }
    
        public virtual int SP_SERVICIO_COMIDA(Nullable<decimal> iD_MINUTA, Nullable<decimal> iD_ORDEN)
        {
            var iD_MINUTAParameter = iD_MINUTA.HasValue ?
                new ObjectParameter("ID_MINUTA", iD_MINUTA) :
                new ObjectParameter("ID_MINUTA", typeof(decimal));
    
            var iD_ORDENParameter = iD_ORDEN.HasValue ?
                new ObjectParameter("ID_ORDEN", iD_ORDEN) :
                new ObjectParameter("ID_ORDEN", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_SERVICIO_COMIDA", iD_MINUTAParameter, iD_ORDENParameter);
        }
    }
}
