//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.APP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMUNA
    {
        public decimal ID_COMUNA { get; set; }
        public string DESCRIPCION { get; set; }
        public decimal ID_PROVINCIA { get; set; }
        public decimal ID_REGION { get; set; }
    
        public virtual PROVINCIA PROVINCIA { get; set; }
    }
}
