//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.APP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLEADO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMPLEADO()
        {
            this.ORDEN_COMPRA = new HashSet<ORDEN_COMPRA>();
            this.ORDEN_PEDIDO = new HashSet<ORDEN_PEDIDO>();
        }
    
        public string RUT_EMP { get; set; }
        public string NOMBRE_EMP { get; set; }
        public string APELLIDOPATERNO_EMP { get; set; }
        public string APELLIDOMATERNO_EMP { get; set; }
        public System.DateTime FECHANACIMIENTO_EMP { get; set; }
        public decimal TELEFONO_EMP { get; set; }
        public System.DateTime FECHAINGRESO_EMP { get; set; }
        public decimal ID_SEXO { get; set; }
        public string USUARIO_EMAIL { get; set; }
    
        public virtual SEXO SEXO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDEN_COMPRA> ORDEN_COMPRA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDEN_PEDIDO> ORDEN_PEDIDO { get; set; }
    }
}
