//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.APP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MINUTA_SEMANAL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MINUTA_SEMANAL()
        {
            this.PLATOS_MINUTA = new HashSet<PLATOS_MINUTA>();
        }
    
        public decimal ID_MINUTA { get; set; }
        public string DESCRIPCION { get; set; }
        public decimal PRECIO_MIN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PLATOS_MINUTA> PLATOS_MINUTA { get; set; }
    }
}
